name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run:
          xcodebuild clean test -project BackApp.xcodeproj -scheme "Back App iOS Debug" -destination "${destination}"
        #bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
